# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBxzkEIG9QLPmhpqL79ylCd7URNer_IO
"""

# Лабораторная работа №6
# Вариант 48. Электросамокаты


import numpy as np

file_path = 'data_variant_48.csv'

dtype = np.dtype([
    ('ts', np.int32),       # временная метка
    ('scoot_id', np.int16), # идентификатор самоката
    ('batt', np.float32),   # заряд батареи
    ('km', np.float32),     # пробег в километрах
    ('sp', np.float32),     # скорость
    ('unlocks', np.uint16)  # количество разблокировок
])

data = np.genfromtxt(
    file_path,
    delimiter=',',
    skip_header=1,
    dtype=dtype
)

print('Файл успешно загружен.')

import pandas as pd
rows_count = data.shape[0]

# вес файла
memory_bytes = data.nbytes
memory_mb = memory_bytes / (1024 ** 2)

print(f'Кол-во строк: {rows_count}')
print(f'Обьем памяти: {memory_bytes} байт')
print(f'Обьем памяти: {memory_mb:.2f} МБ')

print(pd.read_csv(file_path).head(10))

import pandas as pd
rows_count = data.shape[0]

# вес файла
memory_bytes = data.nbytes
memory_mb = memory_bytes / (1024 ** 2)

print(f'Кол-во строк: {rows_count}')
print(f'Обьем памяти: {memory_bytes} байт')
print(f'Обьем памяти: {memory_mb:.2f} МБ')

print(pd.read_csv(file_path).head(10))

numeric_fields = ['batt', 'km', 'sp']

#проход по каждому числовому полю
for field in numeric_fields:
    nan_count = np.isnan(data[field]).sum()
    inf_count = np.isinf(data[field]).sum()
    invalid_count = nan_count + inf_count

    invalid_percent = invalid_count / rows_count * 100

    print(f'Поле {field}:')
    print(f'  NaN: {nan_count}')
    print(f'  Inf: {inf_count}')
    print(f'  Всего некорректных: {invalid_count} ({invalid_percent:.2f}%)')

    if invalid_percent > 3:
        print(' Предупреждение: превышен порог 3%')

np.save('stage1_raw.npy', data)
print('Массив сохранён в файл stage1_raw.npy')

# 2 этап
rows_count = data.shape[0]

# маска для аномалий
mask_batt = (data['batt'] < 0) | (data['batt'] > 100)
mask_sp = data['sp'] < 0
mask_unlocks = data['unlocks'] < 0

# если одно - строка аномальная
anomaly_mask = mask_batt | mask_sp | mask_unlocks

anomaly_count = anomaly_mask.sum()
anomaly_percent = anomaly_count / rows_count * 100

print(f'Количество строк с аномалиями: {anomaly_count}')
print(f'Доля аномальных строк: {anomaly_percent:.2f}%')

# отриц. пробег (нет в условии варианта)
km_negative_mask = data['km'] < 0

km_negative_count = km_negative_mask.sum()
km_negative_percent = km_negative_count / rows_count * 100

print('Дополнительный анализ поля km:')
print(f'Отрицательных значений пробега: {km_negative_count}')
print(f'Доля отрицательных km: {km_negative_percent:.2f}%')

clean_data = data.copy()

# batt - диапазон [0,100]
clean_data['batt'] = np.clip(clean_data['batt'], 0, 100)

# sp < 0 -> 0
clean_data['sp'] = np.where(clean_data['sp'] < 0, 0, clean_data['sp'])

# unlocks < 0 -> 0
clean_data['unlocks'] = np.where(clean_data['unlocks'] < 0, 0, clean_data['unlocks'])

# km < 0 -> 0
clean_data['km'] = np.where(clean_data['km'] < 0, 0, clean_data['km'])

print('Очистка выполнена.')

clean_data['km'] = np.clip(clean_data['km'], 0, 300)
clean_data['sp'] = np.clip(clean_data['sp'], 0, 80)

print('Выбросы обрезаны:')
print('km -> [0, 300]')
print('sp -> [0, 80]')

np.save('stage2_clean.npy', clean_data)
print('Массив сохранён: stage2_clean.npy')

# 3 этап (получение групп)
# уник. значения самокатов
maxi = np.argmax(group_counts)
mini = np.argmin(group_counts)
group_ids, inverse_idx, group_counts = np.unique(
    clean_data['scoot_id'],
    return_inverse=True,
    return_counts=True
)

groups_count = group_ids.size

ostt = rows_count - (group_counts[mini] + group_counts[maxi])

print(f'Количество групп: {groups_count}')
print('Первые 10 групп и их мощности:')

for i in range(min(100, groups_count)):
    print(f'scoot_id = {group_ids[i]} | строк = {group_counts[i]}')

print('Большая группа:')
print(f'Группа = {group_ids[maxi]}')
print(f'Строк = {group_counts[maxi]}')

print('Меньшая группа:')
print(f'Группа = {group_ids[mini]}')
print(f'Строк = {group_counts[mini]}')

print('Кол-во ост.строк:')
print(f'Строк = {ostt}')

group_mean_km = np.zeros(groups_count, dtype=np.float32) # средний пробег
group_std_km = np.zeros(groups_count, dtype=np.float32) # стандарт. откл. пробега
group_max_sp = np.zeros(groups_count, dtype=np.float32) # max speedd

for i in range(groups_count):
    mask = inverse_idx == i

    km_values = clean_data['km'][mask]
    sp_values = clean_data['sp'][mask]

    # счет статы (игнор nan от)
    group_mean_km[i] = np.nanmean(km_values)
    group_std_km[i] = np.nanstd(km_values)
    group_max_sp[i] = np.nanmax(sp_values)

print('Групповая статистика рассчитана.')

print('Первые 10 групп:')

for i in range(min(10, groups_count)):
    print(
        f'ID самоката={group_ids[i]} | '
        f'записей={group_counts[i]} | '
        f'средний пробег={group_mean_km[i]:.2f} км | '
        f'разброс пробега={group_std_km[i]:.2f} км | '
        f'макс. скорость={group_max_sp[i]:.2f} км/ч'
    )

# z = (значение − среднее) / стандартное_отклонение
norm_km = np.zeros(rows_count, dtype=np.float32)

for i in range(groups_count):
    mask = inverse_idx == i

    mean_val = group_mean_km[i]
    std_val = group_std_km[i]

    if std_val == 0:
        std_val = 1.0

    norm_km[mask] = (clean_data['km'][mask] - mean_val) / std_val

print('Z-score нормализация выполнена.')

new_dtype = clean_data.dtype.descr + [('km_zscore', np.float32)]

norm_data = np.empty(clean_data.shape, dtype=new_dtype)

for name in clean_data.dtype.names:
    norm_data[name] = clean_data[name]

norm_data['km_zscore'] = norm_km

print('Новое поле km_zscore добавлено.')

np.save('stage3_normalized.npy', norm_data)
print('Массив сохранён: stage3_normalized.npy')

# 4 этап (скольз ср km)
k = 35

km_values = norm_data['km'].astype(np.float64)

cumsum_km = np.cumsum(np.insert(km_values, 0, 0.0))

km_ma = (cumsum_km[k:] - cumsum_km[:-k]) / k

km_ma = np.pad(km_ma, (k - 1, 0), mode='edge')

print('Скользящее среднее рассчитано.')
print(f'Размер массива: {km_ma.shape[0]}')

# замер расхода батареи между соседними эл-ми
batt_values = norm_data['batt'].astype(np.float32)

batt_diff = np.diff(batt_values)

batt_diff = np.insert(batt_diff, 0, 0)

print('Разница заряда рассчитана.')
print(f'Размер массива: {batt_diff.shape[0]}')

new_dtype = norm_data.dtype.descr + [
    ('km_ma35', np.float32),
    ('batt_diff', np.float32)
]

stage4_data = np.empty(norm_data.shape, dtype=new_dtype)

for name in norm_data.dtype.names:
    stage4_data[name] = norm_data[name]

stage4_data['km_ma35'] = km_ma.astype(np.float32) # скольз ср пробега
stage4_data['batt_diff'] = batt_diff.astype(np.float32) # изм заряда батареи

print('Новые поля добавлены:')
print('km_ma35')
print('batt_diff')

print('Первые 10 строк:')

for i in range(10):
    print(
        f'km={stage4_data["km"][i]:.2f} | '
        f'km_ma35={stage4_data["km_ma35"][i]:.2f} | '
        f'batt_diff={stage4_data["batt_diff"][i]:.2f}'
    )

np.save('stage4_window_diff.npy', stage4_data)
print('Массив сохранён: stage4_window_diff.npy')

# 5 этап (по ср. пробегу за разблокировку, отношение скорости к заряду)
eps = 1e-8

# ср. пробег за разблокировку (общий пробег / кол-во броней)
km_per_unlock = stage4_data['km'] / (stage4_data['unlocks'] + eps)
# отн. скорости к заряду
sp_per_batt = stage4_data['sp'] / (stage4_data['batt'] + eps)

print('Новые признаки рассчитаны.')

km_per_unlock = np.where(np.isfinite(km_per_unlock), km_per_unlock, 0)
sp_per_batt = np.where(np.isfinite(sp_per_batt), sp_per_batt, 0)

print('NaN и Inf заменены на 0.')

new_dtype = stage4_data.dtype.descr + [
    ('km_per_unlock', np.float32),
    ('sp_per_batt', np.float32)
]

stage5_data = np.empty(stage4_data.shape, dtype=new_dtype)

for name in stage4_data.dtype.names:
    stage5_data[name] = stage4_data[name]

stage5_data['km_per_unlock'] = km_per_unlock.astype(np.float32) # пробег за бронь
stage5_data['sp_per_batt'] = sp_per_batt.astype(np.float32) # отн. скорости к заряду

print('Новые поля добавлены.')

print('Первые 10 строк:')

for i in range(10):
    print(
        f'km={stage5_data["km"][i]:.2f} | '
        f'unlocks={stage5_data["unlocks"][i]} | '
        f'km_per_unlock={stage5_data["km_per_unlock"][i]:.4f} | '
        f'sp_per_batt={stage5_data["sp_per_batt"][i]:.4f}'
    )

np.save('stage5_features.npy', stage5_data)
print('Массив сохранён: stage5_features.npy')

# 6 этап

# маска для записей, где скорость > 20 и заряд > 20.
# чтобы отсеить медленные либо стоячие поездки на разряженных самокатах
condition_mask = (
    (stage5_data['sp'] > 20) &
    (stage5_data['batt'] > 20)
)

selected_count = condition_mask.sum()
selected_percent = selected_count / rows_count * 100

print(f'Строк удовлетворяющих условию: {selected_count}')
print(f'Доля выборки: {selected_percent:.2f}%')

# создание таблицы с фильрацией (для ячейки выше)

conditional_table = np.zeros((groups_count, 4), dtype=np.float32)

for i in range(groups_count):
    group_mask = inverse_idx == i
    final_mask = group_mask & condition_mask

    values = stage5_data['km'][final_mask]

    conditional_table[i, 0] = group_ids[i]

    valid_values = values[~np.isnan(values)]

    if valid_values.size > 0:
        conditional_table[i, 1] = np.nanmean(valid_values)
        conditional_table[i, 2] = np.nanmedian(valid_values)
        conditional_table[i, 3] = np.nanpercentile(valid_values, 90)
    else:
        conditional_table[i, 1:] = 0

print('Условная агрегация выполнена.')

print('Первые 10 групп:')
print('group_id | mean_km | median_km | p90_km')

for i in range(10):
    print(
        f'{int(conditional_table[i,0])} | '
        f'{conditional_table[i,1]:.2f} | '
        f'{conditional_table[i,2]:.2f} | '
        f'{conditional_table[i,3]:.2f}'
    )

result_table = conditional_table[:, :3]

print('Финальная таблица формы (N_groups, 3) создана.')
print(result_table.shape)

np.save('stage6_conditional.npy', result_table)
print('Таблица сохранена: stage6_conditional.npy')

# 7этап
import numpy as np

stage7_data = stage5_data.copy()
group_ids, inverse_idx, group_counts = np.unique(
    stage7_data['scoot_id'],
    return_inverse=True,
    return_counts=True
)

groups_count = group_ids.size
rows_count = stage7_data.shape[0]

print(f'Количество групп: {groups_count}')
print(f'Количество строк: {rows_count}')

replaced_counts = np.zeros(groups_count, dtype=np.int32)

total_replaced = 0

for i in range(groups_count):
    group_mask = inverse_idx == i

    km_values = stage7_data['km'][group_mask]

    # искл пропуски
    valid_values = km_values[~np.isnan(km_values)]

    if valid_values.size == 0:
        continue

    q1 = np.percentile(valid_values, 25)
    q3 = np.percentile(valid_values, 75)

    median_val = np.median(valid_values)

    iqr = q3 - q1

    # нижняя и верхняя границы выбросов
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    outlier_mask = group_mask & (
        (stage7_data['km'] < lower) |
        (stage7_data['km'] > upper)
    )

    count_replace = outlier_mask.sum()

    # замена выбросов медианой группы
    stage7_data['km'][outlier_mask] = median_val

    replaced_counts[i] = count_replace
    total_replaced += count_replace

print('Обработка выбросов завершена.')

replaced_percent = total_replaced / rows_count * 100

print(f'Всего заменено значений: {total_replaced}')
print(f'Доля изменённых записей: {replaced_percent:.2f}%')

print('Первые 10 групп:')
print('group_id | replaced_count') # замененные выбросы

for i in range(10):
    print(f'{group_ids[i]} | {replaced_counts[i]}')

np.save('stage7_iqr.npy', stage7_data)
print('Массив сохранён: stage7_iqr.npy')

# 8 этап. логические нарушения

# заряд - 0? скорость тогда тоже 0
rule1 = (stage7_data['batt'] == 0) & (stage7_data['sp'] > 0)

# разблокировок 0? самокат не используется
rule2 = (stage7_data['unlocks'] == 0) & (stage7_data['sp'] > 0)

# скорость у самоката? пробег не может быть 0
rule3 = (stage7_data['sp'] > 0) & (stage7_data['km'] == 0)

logic_mask = rule1 | rule2 | rule3

violations_count = logic_mask.sum()
violations_percent = violations_count / rows_count * 100

print(f'Количество нарушений: {violations_count}')
print(f'Доля нарушений: {violations_percent:.2f}%')

print('По правилам:')

print(f'Нет заряда, но есть движение: {rule1.sum()}')
print(f'Нет разблокировок, но есть движение: {rule2.sum()}')
print(f'Есть скорость, но km = 0: {rule3.sum()}')

stage8_data = stage7_data.copy()

# Если нет заряда - скорость = 0
stage8_data['sp'] = np.where(
    stage8_data['batt'] == 0,
    0,
    stage8_data['sp']
)

# Если нет unlocks - скорость = 0
stage8_data['sp'] = np.where(
    stage8_data['unlocks'] == 0,
    0,
    stage8_data['sp']
)

# Если km = 0 и есть скорость - km = среднее малое значение 1
stage8_data['km'] = np.where(
    (stage8_data['km'] == 0) & (stage8_data['sp'] > 0),
    1,
    stage8_data['km']
)

print('Коррекция выполнена.')

bad_idx = np.where(logic_mask)[0][:10]

print('Первые 10 исправленных строк:')

for idx in bad_idx:
    print(
        f'idx={idx} | '
        f'batt={stage8_data["batt"][idx]:.2f} | '
        f'km={stage8_data["km"][idx]:.2f} | '
        f'sp={stage8_data["sp"][idx]:.2f} | '
        f'unlocks={stage8_data["unlocks"][idx]}'
    )

np.save('stage8_logic.npy', stage8_data)
print('Массив сохранён: stage8_logic.npy')

# 9 этап
cat_ids, cat_counts = np.unique(
    stage8_data['scoot_id'],
    return_counts=True
)

threshold = rows_count * 0.01

print(f'Порог редкой категории: {threshold:.0f} строк')
print(f'Количество категорий: {cat_ids.size}')

rare_mask = cat_counts < threshold

rare_ids = cat_ids[rare_mask]
rare_counts = cat_counts[rare_mask]

print(f'Редких категорий найдено: {rare_ids.size}')
print('Первые 10 редких категорий:')

for i in range(min(10, rare_ids.size)):
    print(f'ID={rare_ids[i]} | count={rare_counts[i]}')

stage9_data = stage8_data.copy()

replace_mask = np.isin(stage9_data['scoot_id'], rare_ids)

# Замена редких категорий на код OTHER = 255
stage9_data['scoot_id'] = np.where(
    replace_mask,
    255,
    stage9_data['scoot_id']
)

print('Редкие категории объединены в OTHER = 255')

new_ids, new_counts = np.unique(
    stage9_data['scoot_id'],
    return_counts=True
)

print('Первые 15 категорий после объединения:')

for i in range(min(15, new_ids.size)):
    print(f'ID={new_ids[i]} | count={new_counts[i]}')

print('Категория OTHER:')
print(f'ID = {new_ids[-1]}')
print(f'Количество строк = {new_counts[-1]}')

np.save('stage9_final.npy', stage9_data)
print('Финальный массив сохранён: stage9_final.npy')

print('ИТОГОВАЯ СВОДКА')
print('-' * 40)

print(f'Количество строк: {rows_count}')
print(f'Количество групп (scoot_id): {groups_count}')

print(f'Аномальных строк (этап 2): {anomaly_count}')
print(f'Доля аномалий: {anomaly_percent:.2f}%')

print(f'IQR заменено значений (этап 7): {total_replaced}')
print(f'Доля IQR замен: {replaced_percent:.2f}%')

print(f'Логических нарушений (этап 8): {violations_count}')
print(f'Доля нарушений: {violations_percent:.2f}%')

print(f'Редких категорий (этап 9): {rare_ids.size}')
print(f'Строк в OTHER (255): {new_counts[-1]}')

print('-' * 40)

